finalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('home.urls')),
    path('', include('internet_and_data.urls')),
    
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.home_page, name='home'),

]

internet_and_data/urls.py
from django.urls import path

from internet_and_data import views

urlpatterns = [
    path('list-of-products/', views.InternetDataListView.as_view(), name='list_of_products'),
    path('create-request/', views.PhotovoltaicCreateView.as_view(), name='create_form'),
    path('photovoltaic-products/', views.first_detail_view, name='photovoltaic_products'),
    # path('photovoltaic-products/', views.PhotovoltaicListView.as_view(), name='photovoltaic_products'),
    path('kit-configuration/', views.choices_view, name='all_choices'),
    path('support/', views.support_view, name='support'),
    path('contact/', views.ContactCreateView.as_view(), name='contact')


]

internet_and_data/models.py
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.html import strip_tags

from finalProject import settings


class InternetData(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='static/internet_data')

    def __str__(self):
        return f'{self.name}'


class Photovoltaic(models.Model):
    MONTHLY_CONSUM_CHOICES = (('up_to_500 kW_monthly', 'Până la 500 kW/lună'),
                              ('between_500_and_1000 kW_monthly', ' Între 500 și 1000 kW/lună'),
                              ('over_1000 kW_monthly', 'Peste 1000 kW/lună'))
    ROOF_TYPE_CHOICES = (('tile', 'Țiglă'), ('metal_tile', 'Țiglă Metalică'))

    monthly_consum = models.CharField('Consum lunar', max_length=50, choices=MONTHLY_CONSUM_CHOICES)
    roof_type = models.CharField('Tip acoperiș', max_length=30, choices=ROOF_TYPE_CHOICES)
    consumption_file = models.BooleanField('Vreau Dosar Prosumator', default=False)

    def __str__(self):
        return f'{self.monthly_consum}'


class PhotovoltaicProduct(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    technical_details = models.TextField(null=True)
    production_details = models.TextField(null=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, null=True)
    image = models.ImageField(upload_to='static/photovoltaics')

    def __str__(self):
        return f'{self.name}'


class PhotovoltaicFirstDetails(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/photovoltaics')
    description = models.TextField(null=True)

    def __str__(self):
        return f'{self.name}'


class PhotovoltaicKit(models.Model):
    ACCESSORY_TYPE_CHOICES = (('tile', 'Șine, cleme și prinderi: speciale pentru țiglă'),
                              ('metal_tile', 'Șine, cleme și prinderi: speciale pentru țiglă metalică'))

    power = models.CharField(max_length=100, choices=Photovoltaic.MONTHLY_CONSUM_CHOICES)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='static/choices')
    number_of_panels = models.IntegerField()
    accessory = models.CharField(max_length=100, choices=ACCESSORY_TYPE_CHOICES)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    price_with_consumption_file = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        return f'{self.power}'


class GeneralSupport(models.Model):
    image = models.ImageField(upload_to='static/support')
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'


class DetailSupport(models.Model):
    image = models.ImageField(upload_to='static/support')
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nume')
    email = models.EmailField(verbose_name='E-mail')
    phone = models.CharField(max_length=20, verbose_name='Telefon')
    message = models.TextField(max_length=1000, verbose_name='Mesaj')
    date_created = models.DateTimeField(verbose_name='Creat la data', default=timezone.now)

    def __str__(self):
        return f'{self.email} - {self.date_created.date()}'



@receiver(post_save, sender=Contact)
def send_email_for_contact_created(sender, instance: Contact, created, **kwargs):
    if created:
        subject = 'Mesaj client Next Level'
        msg = f'''Salut,
       <br>
       <br> Mesaj nou primit in: <b> {instance.date_created.date()} </b>, ora <b> {instance.date_created.time()} </b>.
       <br> Nume: <b> {instance.name} </b>
       <br> Email: <b> {instance.email} </b>
       <br> Telefon: <b> {instance.phone} </b>
       <br><br>
        Mesaj:
        <br>
        {instance.message}.
        '''
        plain_msg = strip_tags(msg)
        send_mail(
            subject=subject,
            message=plain_msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS],
            html_message=msg
        )

internet_and_data/forms.py
from django import forms
from django.forms import Select, TextInput, EmailInput, Textarea

from internet_and_data.models import Photovoltaic, Contact


class PhotovoltaicForm(forms.ModelForm):
    class Meta:
        model = Photovoltaic
        fields = '__all__'
        widgets = {
            'monthly_consum': Select(attrs={'class':'form-control'}),
            'roof_type': Select(attrs={'class':'form-control'})
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name','email','phone','message']
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Numele tău', 'class':'form-control'}),
            'email': EmailInput(attrs={'placeholder': 'Adresa ta de email ', 'class':'form-control'}),
            'phone': TextInput(attrs={'placeholder': 'Numărul tău de telefon', 'class':'form-control'}),
            'message': Textarea(attrs={'placeholder': 'Mesajul tău', 'class':'form-control','rows':4})
        }

internet_and_data/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from internet_and_data.forms import PhotovoltaicForm, ContactForm
from internet_and_data.models import InternetData, Photovoltaic, PhotovoltaicProduct, PhotovoltaicFirstDetails, \
    PhotovoltaicKit, GeneralSupport, DetailSupport, Contact

class InternetDataListView(ListView):
    template_name = 'internet_and_data/list_of_products.html'
    model = InternetData
    queryset = InternetData.objects.all()
    context_object_name = 'all_products'


class PhotovoltaicCreateView(CreateView):
    template_name = 'internet_and_data/create_form.html'
    model = Photovoltaic
    form_class = PhotovoltaicForm
    success_url = reverse_lazy('all_choices')

    def form_valid(self, form):
        valid = super().form_valid(form)
        print(form.cleaned_data)
        power = form.cleaned_data['monthly_consum']
        accessory = form.cleaned_data['roof_type']
        product_kit = PhotovoltaicKit.objects.filter(power=power, accessory=accessory)

        context = {
            'product_kit': product_kit,
            'consumption_file': form.cleaned_data.get('consumption_file', False)
        }
        return render(self.request, 'internet_and_data/all_choices.html', context)


class ContactCreateView(CreateView):
    model = Contact
    template_name = 'internet_and_data/contact_form.html'
    form_class = ContactForm

    def get_success_url(self):
        url = reverse_lazy('contact')
        print(url)
        if self.request.method == 'POST':
            print('post')
            return url + '?success=1'
        else:
            print('get')
            return url

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['success'] = self.request.GET.get('success', 0)
        return data





# class PhotovoltaicListView(ListView):
#     template_name = 'internet_and_data/photovoltaic_products.html'
#     model = PhotovoltaicProduct
#     queryset = PhotovoltaicProduct.objects.all()
#     context_object_name = 'voltaic_products'
#
# class PhotovoltaicFirstDetailsListView(ListView):
#     template_name = 'internet_and_data/photovoltaic_products.html'
#     model = PhotovoltaicFirstDetails
#     queryset = PhotovoltaicFirstDetails.objects.all()
#     context_object_name = 'voltaic_first_details'

# inlocuiesc cele 2 clase de mai sus (listView's) cu functia de mai jos, pentru a putea
# afisa 2 modele intr-o singura pagina html.

def first_detail_view(request):
    detail = PhotovoltaicFirstDetails.objects.all()
    products = PhotovoltaicProduct.objects.all()
    context = {
        'detail': detail,
        'products': products
    }
    return render(request, 'internet_and_data/photovoltaic_products.html', context)


def choices_view(request):
    product_kit = PhotovoltaicKit.objects.all()
    context = {
        'product_kit': product_kit,
    }
    return render(request, 'internet_and_data/all_choices.html', context)


def support_view(request):
    general = GeneralSupport.objects.all()
    detail = DetailSupport.objects.all()
    context = {
        'general': general,
        'detail': detail
    }
    return render(request, 'internet_and_data/support.html', context)

templates/internet_and_data/all_choices.html
{% extends 'base.html' %}
{% block title %} Configurare Oferta {% endblock %}

{% block content %}

    <h1 class="text-center" style="font-family: Gelasio; font-weight: bold">
        Felicitari! Ești cu un pas mai aproape! </h1>

    <h2 class="text-dark text-center" style="font-family: Gelasio;font-weight: bold">
        Recomandarea Next Level pentru tine: </h2>
    <br>
    <div class="container-fluid col-md-10 offset-md-1 pb-4 px-5">
        <div class="row gy-3">
            {% for choices in product_kit %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card bg-light border-white w3-hover-border-green">
                        <img class="img-fluid" src="{{ choices.image.url }}" alt="Imagine Produs">
                        <div class="card-title text-center">
                            <h4 style="font-weight: bold;font-family: Gelasio"> {{ choices.get_power_display }} </h4>
                        </div>

                        <div class="card-body text-center">
                            <h5 style="font-family: Gelasio"> {{ choices.name }} </h5>
                            <h6 style="font-family: Gelasio"> Număr
                                panouri: {{ choices.number_of_panels }} </h6>
                            <h6 style="font-family: Gelasio">
                                {{ choices.get_accessory_display }} </h6>
                            {% if consumption_file %}
                                <p class="p-2 rounded-3 prices_color text-center">
                                    Preț cu dosar prosumator inclus: {{ choices.price_with_consumption_file }}
                                    RON
                                </p>
                            {% else %}
                                <p class="p-2 rounded-3 prices_color text-center">Preț
                                    referință: {{ choices.price }}
                                    RON
                                </p>
                            {% endif %}

                        </div>

                    </div>

                </div>

            {% endfor %}


        </div>

    </div>

{% endblock %}

templates/internet_and_data/contact_form.html
{% extends 'base.html' %}
{% block content %}
    {% if success == '1' %}
        <div class="alert alert-success alert-dismissible col-md-4 position-relative">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            <strong>Mulțumim!</strong> Am primit mesajul tău!
        </div>
    {% endif %}

    <div class="container-fluid">
        <br>
        <div class="row">

            <div class="col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-header text-center">
                        <br>
                        <h3> Trimite un mesaj: </h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn" style="background-color: rgb(98 127 159); color: white"><i
                                    class="fa-light fa-paper-plane-top"></i> Trimite
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/internet_and_data/create_form.html
{% extends 'base.html' %}
{% block title %} Crează Cerere {% endblock %}

{% block content %}
    <div class="container-fluid">
        <br>
        <div class="row">

            <div class="col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-header text-center">
                        <br>
                        <h3> Introduceți datele: </h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn" style="background-color: rgb(98 127 159); color: white">Confirma</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/internet_and_data/list_of_products.html
{% extends 'base.html' %}
{% block title %} Abonamente Internet si TV {% endblock %}
{#{% block body_style %}background-color: #cc0000{% endblock %}#}
{% block content %}
    <br>
    <div class="container-fluid col-md-10 offset-md-1">
        <div class="row gy-3">
            {% for internet_and_data in all_products %}
                <div class="col-lg-3 col-sm-6 col-12">
                    <div class="card bg-light border-white w3-hover-border-green">
                        <img class="card-img-top" src="{{ internet_and_data.image.url }}" alt="Internet and Data">
                        <div class="card-body text-center">
                            <h5 style="font-weight: bold"> {{ internet_and_data.name }} </h5>
                            <div class="card-text description">
                                {{ internet_and_data.description|safe }}
                            </div>
                            <p class="p-2 rounded-3 prices_color text-center">{{ internet_and_data.price }}
                                RON
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/internet_and_data/photovoltaic_products.html
{% extends 'base.html' %}
{% block title %} Lista de Produse {% endblock %}

{% block content %}
    <div class="bg-light m-2">
        <div class="row g-0">
            {% for photovoltaic in detail %}
                <div class="col-lg-4 offset-lg-1 col-md-4">
                    <img src="{{ photovoltaic.image.url }}" class="img-fluid p-2"
                         alt="Photovoltaic Products">
                </div>
                <div class="col-lg-6 col-md-8">

                    <h3 class="card-title border-bottom" style="color:black; font-family: Gelasio">
                        <strong>{{ photovoltaic.name }}</strong>
                    </h3>

                    <h6 style="text-align: justify">{{ photovoltaic.description|linebreaks|safe }}</h6>


                </div>
            {% endfor %}
        </div>
    </div>
    <div>
        <h4 class="col-md-4 ps-4 py-2 offset-md-1" style="color:black;font-family: Gelasio"><strong><i class="fa-solid fa-check"></i>
            Alege din oferta noastră:</strong></h4>
    </div>

    <div class="container-fluid col-md-10 offset md-1">
        <div class="row gy-3">
            {% for photovoltaic in products %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                    <div class="card bg-light border-white w3-hover-border-light-green">
                        <img class="card-img-top" src="{{ photovoltaic.image.url }}" alt="Photovoltaic Products">
                        <div class="card-body text-center">
                            <h5 style="height:70px">{{ photovoltaic.name }}</h5>

                            <div class="description" id="description_{{ forloop.counter0 }}">
                                <p class="text-start">
                                    Descriere:
                                </p>
                                <h6 class="text-start">{{ photovoltaic.description|linebreaks|safe }}</h6>
                                <p class="text-start">Detalii
                                    Tehnice:</p><h6
                                    class="text-start">{{ photovoltaic.technical_details|linebreaks|safe }}</h6>
                                <p class="text-start">Detalii
                                    Producție:</p><h6
                                    class="text-start">{{ photovoltaic.production_details|linebreaks|safe }}</h6>
                                <div class="fade-out" style="box-shadow: 0 -100px 50px -80px white inset">
                                </div>
                            </div>

                            <div class="card-text">
                                <div class="d-flex justify-content-center py-3">
                                    <button type="button" class="w3-btn" style="font-weight: bold"
                                            data-bs-toggle="modal"
                                            data-bs-target="#exampleModal"
                                            onclick="copyDataToModal('description_{{ forloop.counter0 }}','{{ photovoltaic.name }}')">
                                        Vezi mai mult <i class="fa-solid fa-circle-arrow-right"></i>

                                    </button>
                                </div>
                                <p class="p-2 rounded-3 prices_color text-center">
                                    Preț: {{ photovoltaic.price|safe }} RON</p>
                            </div>

                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
        <div>
            <a class="btn mt-3 px-4" style="background-color: rgb(98 127 159); color: white "
               href="{% url 'contact' %}"><i
                    class="fa-solid fa-share"></i> Trimite-ne un mesaj </a>
        </div>
    </div>

    <script>
        function copyDataToModal(elementId, title) {
            const sourceDiv = document.getElementById(elementId);
            const destinationDiv = document.getElementById('modal_body');
            destinationDiv.innerHTML = sourceDiv.innerHTML;
            const destination_title = document.getElementById('exampleModalLabel');
            destination_title.innerText = title;
        }
    </script>

{% endblock %}

templates/internet_and_data/support.html
{% extends 'base.html' %}
{% block title %} Suport {% endblock %}
{% block content %}
    <div class="bg-light m-2">
        <div class="row g-0">
            {% for item in general %}

                <div class="col-lg-4 offset-lg-1 col-md-4">
                    <img src="{{ item.image.url }}" class="img-fluid p-2" alt="Suport Image">

                </div>
                <div class="col-lg-6 col-md-8">
                    <h3 class="card-title border-bottom text-center" style="color: black; font-family: Gelasio">
                        <strong>{{ item.name }}</strong>
                    </h3>

                    <h5 style="text-align: center; color: black">{{ item.description|linebreaks|safe }}</h5>

                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container-fluid col-md-10 offset-md-1">
        <div class="row gy-3">
            {% for item in detail %}
                <div class="col-lg-4 col-md-4 col-sm-6 col-12 pb-4">
                    <div class="card bg-light border-white w3-hover-border-light-blue">
                        <img class="card-img-top" src="{{ item.image.url }}" alt="Photovoltaic Products">
                        <div class="card-body text-center">
                            <h5 style="font-weight: bold; font-family: Gelasio"> {{ item.name }} </h5>

                            <div class="card_description" id="description_{{ forloop.counter0 }}">

                                <h6 class="text-center">{{ item.description|linebreaks|safe }}</h6>
                                <div class="fade-out" style="box-shadow: 0 -100px 50px -80px white inset">
                                </div>

                            </div>

                            <div class="card-text">
                                <button type="button" class="w3-btn m-1 px-5" style="font-weight: bold"
                                        data-bs-toggle="modal"
                                        data-bs-target="#exampleModal"
                                        onclick="copyDataToModal('description_{{ forloop.counter0 }}','{{ item.name }}')">
                                    Vezi mai mult <i class="fa-solid fa-circle-arrow-right"></i>

                                </button>

                            </div>

                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
        <div>
            <a class="btn mt-3 px-4" style="background-color: rgb(98 127 159); color: white " href="{% url 'contact' %}"><i class="fa-solid fa-share"></i>
                Trimite-ne un mesaj </a>
        </div>
    </div>


    <script>
        function copyDataToModal(elementId, title) {
            const sourceDiv = document.getElementById(elementId);
            const destinationDiv = document.getElementById('modal_body');
            destinationDiv.innerHTML = sourceDiv.innerHTML;
            const destination_title = document.getElementById('exampleModalLabel');
            destination_title.innerText = title;
        }
    </script>

{% endblock %}